// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

import { defineConfig } from "@prisma/config";

export default defineConfig({
  schema: "./prisma/schema.prisma",
  datasource: {
    // 環境変数 DATABASE_URL から接続先を読み込む設定じゃ
    url: process.env.DATABASE_URL,
  },
});
